### ISSUE TITLE
Practica Proposiciones

### ISSUE THREAD

**Issue by ghost** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-Diego0501#1]
[Practica3 proposiciones_DiegoSosa.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-Diego0501/files/13197201/Practica3.proposiciones_DiegoSosa.pdf)

**Comment by elisa1223** [comment]
Portada: 25%
Procedimiento: 25%
Figuras,ilustraciones y fotografias: 25%
Resultados y conclusiones: 25%

Calificación final: 20/20
Evaluado por el equipo de Elisa.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
